name: deploy

on:
  push:
    branches:
      - main

permissions:        # <--- 新增這一段
  contents: write   # <--- 賦予寫入權限

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        run: hugo --minify

     - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          force_orphan: true  # <--- 加入這一行，確保不會與舊紀錄衝突
          publish_branch: gh-pages
